apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    name: front-end-service
    app: guest-book-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: front-end-pod
    app: guest-book-app
