apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  labels:
    name: front-end-deployment
    app: guest-book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end-pod
      app: guest-book-app
  template:
    metadata:
      name: front-end-pod
      labels:
        name: front-end-pod
        app: guest-book-app
    spec:
      containers:
        - name: front-end
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
          - containerPort: 80
