apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    name: redis-slave
    app: guest-book-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: guest-book-app
